# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit overview-single-source.Rmd to modify this file

## ---- Rlogo, echo=FALSE, fig.cap='The logo of R.', out.width='2in', fig.align='center', fig.pos='htbp'----
knitr::include_graphics('Rlogo.pdf')


## -----------------------------------------------------------------------------
library(extraDistr)
library(countreg)
library(VGAM)
library(brms)
library(numDeriv)


## -----------------------------------------------------------------------------
library(extraDistr)
set.seed(123)


## -----------------------------------------------------------------------------
x <- 1:10
plot(x)

